### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by SergeyVR** [deitch/searchjs#19]
Since I registred searchjs as bower package I have some problems with injecting it with [wiredep](https://github.com/taptapship/wiredep) tool.
After bower install it has following bower.json file
`{
  "name": "searchjs",
  "homepage": "https://github.com/deitch/searchjs",
  "version": "0.8.0",
  "_release": "0.8.0",
  "_resolution": {
    "type": "version",
    "tag": "0.8.0",
  },
  "_source": "https://github.com/deitch/searchjs.git",
  "_target": "^0.8.0",
  "_originalSource": "searchjs"
}`

Is it possible to add fields in it?
  "dependencies": {},
  "main": "./lib/searchjs.js",

**Comment by deitch** [comment]
It already has `"main": "./lib/searchjs.js",` see https://github.com/deitch/searchjs/blob/master/package.json#L24

For `dependencies:{}` in https://github.com/deitch/searchjs/blob/master/package.json , I don't see why not, but how will that help?

**Comment by SergeyVR** [comment]
I know that this fields are exists in package.json but unfortunately they are missed in generated bower.json 
:(

**Comment by deitch** [comment]
Do you know how it gets generated for the `bower.json`? I know very little about the bower process. As it is, searchjs has no dependencies, so maybe that?

**Comment by SergeyVR** [comment]
Unfortunately I don't know how it gets generated bower.json . I have only one assumption: it's need to be  unregistered from bower repository and register it again with submiting a ticket in the [Bower Registry repo](https://github.com/bower/registry) how it's described in [bower documentation](https://bower.io/docs/creating-packages/)

P.S. Additionaly I would like to thank you for your participation in this discussion and to wish you success with your project. I think it's it has the prospects of further development.

**Comment by deitch** [comment]
> I think it's it has the prospects of further development.

It needs a lot of work, indeed. Thanks!
