### ISSUE TITLE
Suport travis and codeconv

### ISSUE THREAD

**Issue by hjemmel** [deitch/searchjs#23]
Hey @deitch What you thing to add support for travis CI and/or codcov ? Just an idea! :)

**Comment by deitch** [comment]
Sure, happy to put Travis in. I wouldn't mind automated PR merge = `npm publish` and requiring tests to pass.

**Comment by hjemmel** [comment]
Just made a pull request

**Comment by deitch** [comment]
Let's close this in favour of #27 and continue the conversation there.
