### ISSUE TITLE
Built-in sort

### ISSUE THREAD

**Issue by joeworkman** [deitch/searchjs#26]
I know that its easy enough for me to sort my data after a search, but it could be a nice feature to be able to define a field that the array should be sorted by. 

Thanks for making this, its really saving the day!

**Comment by deitch** [comment]
> Thanks for making this, its really saving the day!

Quite welcome. I no longer can recall what the project was that got it started. It is my hope that all of this will be made unnecessary by some version or ES in the future. In the meantime...

> it could be a nice feature to be able to define a field that the array should be sorted by.

Why not just use the build-in JS capabilities?

```js
> list = [{name:"Jim", age:35},{name:"Sally",age:22},{name:"Alex",age:55}]
> list.sort((a,b) =>{return a.age - b.age})
[ { name: 'Sally', age: 22 },
  { name: 'Jim', age: 35 },
  { name: 'Alex', age: 55 } ]
> list.sort( (a,b) => { return (a.name > b.name) ? 1 : ((b.name > a.name) ? -1 : 0)} )
[ { name: 'Alex', age: 55 },
  { name: 'Jim', age: 35 },
  { name: 'Sally', age: 22 } ]
```

**Comment by joeworkman** [comment]
You are correct. I just though that it would be nice if I could simply give a list of fields to sort by and the library would take care of it. Its purely a convenience thing...

**Comment by deitch** [comment]
Hmm. Can you give an example of what the interface would look like?

**Comment by joeworkman** [comment]
Sorry. I totally missed your reply. I was thinking something like this to sort the data by a specific property. 

`{name:"John",age:30,_sort:"name"}`

**Comment by joeworkman** [comment]
Good points on the integer sorting. I could see this as not being as simple a solution as I originally intended.

**Comment by deitch** [comment]
I tend to think in the Unix philosophy of doing one thing, and doing it well, and having a well-defined (normally char stream) interface. In this case, `matchArray()` _always_ returns a JS array, which can be chained to another sorting function.

I think we should let this one go for now.
