### ISSUE TITLE
Search with type coercion

### ISSUE THREAD

**Issue by mikecole** [deitch/searchjs#34]
Am I correct that the properties have to be the same type to match?

For example, given:

`var list = [{name:"John",age:25},{name:"Jill",age:30}];`

This would match:
`{name:"John",age:30}`

This would not match:
`{name:"John",age:'30'}`

**Comment by deitch** [comment]
Correct @mikecole . Here is an example. See how the matches are performed.

```js
> search = require('searchjs')
{ setDefaults: [Function: setDefaults],
  resetDefaults: [Function: resetDefaults],
  singleMatch: [Function: singleMatch],
  matchArray: [Function: matchArray],
  matchObject: [Function: matchObject] }
> ary = [{name:"string",age:"30"},{name:"number",age:30}]
[ { name: 'string', age: '30' }, { name: 'number', age: 30 } ]
> search.matchArray(ary,{age:30})
[ { name: 'number', age: 30 } ]
> search.matchArray(ary,{age:"30"})
[ { name: 'string', age: '30' } ]
```

**Comment by mikecole** [comment]
I can work with this, I think. My search term is a free-form text field so I can check the datatype and if it can parse to int I'll add both terms. Thanks!
