### ISSUE TITLE
Date queries

### ISSUE THREAD

**Issue by joeworkman** [deitch/searchjs#35]
I know that this may be tough since dates could be stored in so many formats. However, it would be really cool if we could query by date. Could this somehow be done with existing APIs and moment.js?

**Comment by deitch** [comment]
I like the idea. We would need to treat it like we do numbers, supporting the range terms [here](https://github.com/deitch/searchjs#range).

Let's use this as a tracking issue. It is easiest if we just convert dates to epoch times, then treat them as numbers. Anything that already is in epoch, e.g. `{date: 1234567}` is easy to handle with the existing library.

Questions to answer:

* What formats would we support to start?
* How would we handle timezones? I don't want to reimplement https://github.com/deitch/jsorm-i18n in here, nor do I want us to try and reimplement [momentjs](https://momentjs.com).
* What would the interface look like?

Is this easiest to start by having a plugin format? E.g. you can pass it a "date converter" that will convert any date fields prior to comparison, so you can plug in my old i18n lib or momentjs or your own custom one? If so, we would need some indicator that a field is to be treated as date and converted.

**Comment by joeworkman** [comment]
I used to store all dates as epoch time as well. Then I read this amazing piece... https://zachholman.com/talk/utc-is-enough-for-everyone-right

Now I store things as ISO8601 format. It makes things much more readable when simply reading the data as well. 

I think that it would be important not to reinvent the wheel around time. Your idea about making some sort of plugin architecture makes a lot of sense. Then a plugin for moment or any other JS library could be used. 

As for interface? Here are some ideas. The `_ext` could be used to tell that its going to use the `moment` extension. 

```
{ tags : [ "web" , "development" ] , date : { _ext: "moment",  from: "2018-10-01", to: "2018-10-31" } }
{ tags : [ "web" , "development" ] , date : { _ext: "moment",  after: "2018-10-01" } }
{ tags : [ "web" , "development" ] , date : { _ext: "moment",  before: "2018-10-01" } }
```

**Comment by joeworkman** [comment]
Interesting. I will play around with converting to Date objects to see how I can get along with that. 

I assume that means that I would need to convert all of the dates in my data to be date objects instead of strings as well.

**Comment by deitch** [comment]
> I assume that means that I would need to convert all of the dates in my data to be date objects instead of strings as well.

The way it works now, yes. It knows how to compare `Date` to `Date`. Ideally, we would be more flexible than that, but it is a start.

**Comment by joeworkman** [comment]
Time flies when you are having fun! I have finally been integrating Date logic into the queries in my app. They are working like a charm! I even got moments working... 

```
SEARCHJS.matchArray(data, {releaseDate: {from:moment().subtract(1,"year").toDate()}});
```

Since I am passing my search queries via JSON, I will have to make some special syntax that will allow me to convert the jsql on the fly. 

I will close this issue, since the way you implemented things really does work well. Thanks!
