### ISSUE TITLE
Text ranges

### ISSUE THREAD

**Issue by mikecole** [deitch/searchjs#36]
From the list:
```
[{name: 'larry'}, {name: 'moe'}, {name: 'curly'}]
```
I'd like to query for names between c and l, so in this case it would exclude moe. I tried the following:

```
{name: {from: 'c', to: 'l')}
```
but it seems this isn't supported out of the box. Is there a way to easily do this using searchjs? And furthermore, I'm eventually going to want to do more complex ranges like `{name: {from: 'cu', to: 'la')}`

**Comment by joeworkman** [comment]
I think that a more extensible use case would be to have regex support. Then you could write your regex to be whatever you want.

**Comment by mikecole** [comment]
I don't disagree with you there, but I feel like range validation that you can do with straight JS should be fairly easy to implement?

```
'mike' > 'm' === true
'mike' < 'n' === true
'mike' > 'mi' === true
```

**Comment by joeworkman** [comment]
I have to say that I didn't even know that was possible in JS... learn something new everyday!

**Comment by deitch** [comment]
I like the idea of both of them, but, yeah @mikecole , we can get that out of the box. Right now it uses `from` and `to` purely on numbers and dates, see [here](https://github.com/deitch/searchjs/blob/master/src/searchjs.js#L27-L37), but there is no reason we cannot extend that to general strings as well. The API doesn't change, it just handles it a little differently if it is strings.

Want to open a PR to fix and add a test case?

**Comment by deitch** [comment]
As for regex, open a new issue for it @joeworkman , we can figure out the API there and then look at implementation.
