### ISSUE TITLE
Broken packages

### ISSUE THREAD

**Issue by bmaland** [deitch/searchjs#45]
Hi, both searchjs@0.15.1 and searchjs@0.15.2 seem to have broken packages on npm (no js files included in the packages). 0.15.0 is the last working version

**Comment by timelyportfolio** [comment]
@bmaland I just saw this as well.

![image](https://user-images.githubusercontent.com/837910/45901664-56e87e00-bda9-11e8-9a36-14e815e7e971.png)

**Comment by timelyportfolio** [comment]
Looks like `npm scripts` has now changed to not run `build` https://docs.npmjs.com/misc/scripts.  Seems like we need to change `build` to something else or add another script, such as `prepublish` or `pretest`.

**Comment by deitch** [comment]
Well, ugh. 

What exactly changed?

**Comment by deitch** [comment]
OK, yeah, I see. I had to refresh my memory. I will fix this for a new release rather than force-patching the existing one.

I have been meaning to bundle this as a 1.0.0 finally. I will do a PR and patch with a `prepublish` to `npm build`, and then release a 1.0.0

**Comment by deitch** [comment]
OK go check out the finally release `1.0.0`

**Comment by timelyportfolio** [comment]
@deitch looks great, thanks!
