### ISSUE TITLE
Hello good searching tool ! question please

### ISSUE THREAD

**Issue by mistertest** [deitch/searchjs#5]
Hello,
I'm french i use your search.js, it's work well with my json.
I use it for my project with 2 json files, one json file for term to search and one json file for searching in this terms and matching.

How can i do for this .

I search the film avengers and in result i have the others films of avengers 
and i want just the first film.

I used        var results = SEARCHJS.matchArray(datax,{titre: avengers, _text:true}); 

Thank you for help.
Best regards.

**Comment by deitch** [comment]
Bonjour @mistertest ca me fait plaisir de vout connaitre. (my French is not as good as it was; I am originally from Montréal, but that was a long time ago)

Can you paste in some of your sample data, or a jsfiddle with the data?

**Comment by deitch** [comment]
No comment in better part of a year. Closing issue. If still a problem, please reopen.
