### ISSUE TITLE
Nested AND Join

### ISSUE THREAD

**Issue by mbrahimi617** [deitch/searchjs#54]
I have a JSON array of firmware data for which I would like to find any rows whose `name` property contains the search query or whose `supports` key contains a JSON object with `release` equal to the search query and a release that begins with Y. The name part of the `OR` seems to work just fine. However, when I enter a release in my application, I get all of the entries presumably because each of them contain at least one support with a `value` beginning with Y. However, I need the release condition to be matched at the same time, hence the `AND` join. Any ideas why this isn't working? 

<pre>
const FIRMWARE = {_join: "OR", terms: [

  {name: text, _text: true}, 

  {_join: "AND", "terms": [

    {"supports.release": text, _word: true},

    {"supports.value": "Y", _start: true}

  ]}

]};
</pre>

**Comment by deitch** [comment]
It looks like it makes sense. Can you upload some sample code, with the above terms and some sample inputs, so I can run it and recreate the error?

**Comment by mbrahimi617** [comment]
Attached is a sample dump of data. I simply call `matchArray` on the data. Let's say the search text was `3.7.9` for example. As of now, I'm getting all the elements in the array. However, I only expect the following:

<pre>
820-000001-dell-r720xdfirmware-n
820-000001-dell-r720xdfirmware-m
820-000001-dell-r720xdfirmware-k
</pre>
[dump.zip](https://github.com/deitch/searchjs/files/3461905/dump.zip)

**Comment by mbrahimi617** [comment]
Any updates on why this isn't working as expected?

**Comment by deitch** [comment]
Ouch. 974 lines of entry. For future issues, please provide a simple and fully runnable example with minimal data to prove it.

In this case, I am not actually sure what you are searching for. Looking at your search text:

```json
const FIRMWARE = {_join: "OR", terms: [
  {name: text, _text: true}, 
  {_join: "AND", "terms": [
    {"supports.release": text, _word: true},
    {"supports.value": "Y", _start: true}
  ]}
]};
```

You have `name:text`. Is `text` a var? What is it set to? Same for `"supports.release": text`?

**Comment by mbrahimi617** [comment]
I gave you a sample execution in the previous comment. The `text` variable holds a string value of `3.7.9` for which it should find the objects in the array, which I will denote by their `name` field.

<pre>
820-000001-dell-r720xdfirmware-n
820-000001-dell-r720xdfirmware-m
820-000001-dell-r720xdfirmware-k
</pre>

**Comment by mbrahimi617** [comment]
Do you understand the premise of the search use case now?

**Comment by deitch** [comment]
Mostly. Can you please put together a fully working example, single file, that we can download and run `node file.js` (or whatever you name it), that includes sample data and the search terms from above, and gives the (in this case incorrect) output? It may take "just 5 minutes", but you should make this as simple as possible.

**Comment by mbrahimi617** [comment]
I've reiterated the same test case numerous times. I'm not exactly sure how to create an environment or a single file which includes your package. I'm currently running it in a React project with `searchjs` as an imported via ES6. That being said, my file won't match your expectations, so I'm just going to quit while I'm ahead.
