### ISSUE TITLE
Combining terms with other filters.

### ISSUE THREAD

**Issue by CGeorges** [deitch/searchjs#56]
I'm trying to apply multiple filters on an array of big objects like so 
`filters: {
      terms: [
        {
          _join: 'OR',
          terms: [
            {
              description: 'modular',
              _text: true
            },
            {
              title: 'modular',
              _text: true
            }
          ]
        }
      ],
      'categories.name': 'Environments',
      'tags.name': [
        'LOWPOLY',
        'PALMTREE'
      ]
    }`

the `terms` is a keyword search, one string searched through multiple properties with OR operand, but after applying this `categories.name` and `tags.name` is completely ignored, I'm assuming I'm doing something wrong related to the structure?

My goal is something like so 
`if ( (title.includes('modular') || description.includes('modular')) && categories.name === 'Environments' && tags.name.includes(['PALMTREE', 'LOWPOLY']) )`

**Comment by CGeorges** [comment]
If I remove the `terms` property the other 2 filters work fine

**Comment by CGeorges** [comment]
Figured it's not possible in such a way so I refactored to split them in separate filters

**Comment by deitch** [comment]
You can do it, you just need to merge it all into `terms`. The README [describes primitives and composites](https://github.com/deitch/searchjs#syntax-definition). You can use a primitive or composite, but not together, so the following ignores the primitive terms:

```json
     terms: [
         // lots of terms here
      ],
      'categories.name': 'Environments',  // primitive
      'tags.name': [ // primitive
        'LOWPOLY',
        'PALMTREE'
      ]
```

It is in the code [here](https://github.com/deitch/searchjs/blob/master/src/searchjs.js#L114) as well.

You can get what you want by combining into a single `terms`:

```json
terms: [
   termA, // composite
   termB, // primitive
   termC. // primitive
]
```

Or, in your case:

```json
filters: {
      terms: [
        {
          _join: 'OR',
          terms: [
            {
              description: 'modular',
              _text: true
            },
            {
              title: 'modular',
              _text: true
            }
          ]
        },
        {
          'categories.name': 'Environments',
          'tags.name': [
            'LOWPOLY',
            'PALMTREE'
          ]
        }
      ],
    }
```
