### ISSUE TITLE
Support wildcards in string searching

### ISSUE THREAD

**Issue by m1dst** [deitch/searchjs#65]
It would be great if you could support some wildcards so that string searches could be more like the SQL LIKE syntax.   That would be awesome!

**Comment by deitch** [comment]
Hi @m1dst . Have you seen [text searching](https://github.com/deitch/searchjs#text-searching)? Flag it as `_text: true`, and it will do case-insensitive, any-part-of-the-word matching. So `{_text: true, name: "davi"}` is the moral equivalent of `/davi/`.

Or are you thinking explicitly wildcards, as in a regex? I would be hesitant to throw SQL's syntax in here, as this is a JS lib and is trying to be json-compatible, but I think supporting [js RegEx](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) string representatives might work.

How would we flag that it is a RegExp, and not a regular string? E.g. one person is searching for any usage of `atterso` (from your name), so they look for the RegExp `/atterso/i`, and the other is looking for the literal string `"/atterso/i"`. I don't think I can use real RegExp (as in `/atterso/I`) in json without quoting it, so then it is a string all over again.

**Comment by deitch** [comment]
Nope, I tried, lint gives:

```
Error: Parse error on line 4:
..."/atterso/i",	"c": /atterso/i}
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by deitch** [comment]
I guess we could use a flag `_regexp: true` like we have `_word` and `_text`?

**Comment by m1dst** [comment]
Hi,

A flag might work.  I am basically translating queries from one language to
another.  I could probably translate it to a regex so that would work
perfectly I think.
