### ISSUE TITLE
ESM: NPM package does not contains "src" directory

### ISSUE THREAD

**Issue by matschik** [deitch/searchjs#72]
I'm using an ESM build and you referenced in package.json: "module: src/searchjs.js".
https://github.com/deitch/searchjs/blob/9fd9259ad77fa14be3b778b9022bcaa215f04417/package.json#L30

But in npm package, "./src" directory is not present. Only "./lib" directory. 
Can you publish it with "src" dir ? :)

Thank you and thanks for your great work !

**Comment by deitch** [comment]
I was trying to keep src in the repo and only the build artifacts published, but perhaps that didn't work. I find it interesting that it hadn't come up before.

Can you reproduce your build process to get the error, so I can address it properly?

**Comment by matschik** [comment]
It hadn't come up before because new builders with strict ESM support are emerging:
- Vite.js: https://github.com/vitejs/vite
- Snowpack: https://github.com/pikapkg/snowpack

To reproduce the error, read "Getting started" section in ViteJS repository.
```sh
$ npm install searchjs
```

In a JS/React/Vue file:
```js
import searchjs from "searchjs"

const list = [{name:"John",age:25},{name:"Jill",age:30}];
let matches
matches = searchjs.matchObject(list[0],{name:"Johnny"}); // returns false
matches = searchjs.matchArray(list,{name:"John"}); // returns [{name:"John",age:25}]
```
