### ISSUE TITLE
when querying nested object with numeric IDs, their order influences search results

### ISSUE THREAD

**Issue by paolomaffei** [deitch/searchjs#9]
with a query like {
"path.to.id": [1, 2]
}
results are different then with a query like
"path.to.id": [2, 1]
}

in the pictures, query is second console.log argument, while the third argument is the results (2 and 3 objects respectively)
(I checked that it's not just console.log being not updated in the debugger)

![capture1](https://cloud.githubusercontent.com/assets/2191420/13014288/f49dc8fa-d1aa-11e5-8415-4964f787f6d6.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2191420/13014291/f82bc6b6-d1aa-11e5-81f9-874371570654.PNG)

is this a known problem?

**Comment by deitch** [comment]
I didn't fully understand it. Can you throw up a gist or jsfiddle?

**Comment by paolomaffei** [comment]
https://jsfiddle.net/24v1j8ub/1/

**Comment by deitch** [comment]
Whoa. Here's an updated fiddle. Now we need to understand why it is doing this.

https://jsfiddle.net/24v1j8ub/4/

**Comment by deitch** [comment]
And even further simplified to the single core question: https://jsfiddle.net/24v1j8ub/5/

**Comment by paolomaffei** [comment]
given that this fiddle works just fine https://jsfiddle.net/24v1j8ub/7/
it seems it only happens when the item is the second one of an array of 2 (the third one of an array of 3 works fine, so it's not a "last element" thing
I'm suspecting some off by 1 error...

**Comment by deitch** [comment]
Fixed with 0.7.1

**Comment by paolomaffei** [comment]
thanks!
